[options]
girs_dir = "../gir-files"
library = "GLib"
version = "2.0"
min_cfg_version = "2.32"
target_path = "."
work_mode = "normal"

generate = [
    "GLib.KeyFile",
    "GLib.KeyFileFlags",
]

ignore = [
]

manual = [
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Variant",
    "GLib.VariantType",
    "GObject.Object",
]
